# インクルーシブ教育と合理的配慮

## 障害モデル

障害をどのようなものとして捉えるかによって，障害者への教育や支援のあり方は異なってきます。
障害の捉え方は大きく分けると**医学モデル**と**社会モデル**の2つがあるとされています。

### 医学モデルと社会モデル

障害とは従来は個人が持っているものという考え方でした。
そこでは，障害は病気・外傷などから直接的に生じるものとして捉えられており，障害によって生じる問題は個人に原因があるとされます。
また，障害から生じる問題の解決のためには医療などの専門職による援助を必要とするものとされます。
こうした障害の捉え方を医学モデルと呼びます。

これに対して，障害を様々な障壁と個人との相互作用の中で生じるとする捉え方が1980年代にイギリスにおいて出てきました。 イギリスの障害学の研究者であるオリバー（Oliver）は，障害によって生じる問題は，障害のある人のニーズに応えるための適切なサービスを提供できなかった社会の側に原因があると考え，社会モデルを提唱しました。 社会モデルでは，障害とは社会の中で生じるものなので，社会的な障壁を取り除くことで障害による不便を乗り越えようとします。

具体例で考えてみましょう。
@tbl-models には障害によって生じている問題の状況と，医学モデルと社会モデルにおけるそれぞれの問題解決の方向性の違いを示してあります。

| 状況   | 医学モデル | 社会モデル|
|:-----------------------------|:-------------------|:----------------------|
| 足が動かず車椅子を利用中。階段が登れず，上の階へと移動できない。 | 足の機能を回復するための機能回復訓練を行って登れるようにする。 | エレベータやスロープを設置して，車椅子のままでも上の階へと移動できるようにする。|
| 視力に問題はないものの，文字が読めないため，教科書が読めず授業に参加できない。 | 文字が読めるようにするための専門的な訓練をして，読字能力を鍛えて教科書を読めるようにする。 | デジタル教科書と音声読み上げ機能のあるパソコンを使って内容を理解し，授業に参加できるようにする。 |

: 医学モデルと社会モデルの障害の捉え方の比較 {#tbl-models}

近年ではこうした2つの捉え方を対立させるのでなく統合して捉えようとしており，それを統合モデルと呼ぶこともあります。

## インクルーシブ教育とは

英語のinclusiveには「包括的な」「だれでも参加できる」といった意味があります。
インクルーシブ教育（inclusive education）とは，「だれもが参加できる教育」だと言えそうです。
ここでは，インクルーシブ教育の定義や現状，その課題を学びます。

インクルーシブ教育は，1994年にユネスコとスペイン政府が共催した世界会議で採択された「特別なニーズ教育における原則，政策，実践に関するサラマンカ生命ならびに行動の枠組み」において提唱されました。
その後，2005年にはインクルーシブ教育に関してユネスコが[ガイドライン](https://unesdoc.unesco.org/ark:/48223/pf0000140224)を提案しています。
そのガイドラインを元にして @noguchi2022 は以下のインクルーシブ教育を以下のように定義しています。

:::::: {.callout-note}
## インクルーシブ教育の定義

インクルーシブ教育は，多様な子どもたちがいることを前提とし，その多様な子どもたち（排除されやすい子どもたちを含む）の教育を受ける権利を地域の学校で保証するために，教育システムそのものを改革していくプロセス
:::

ここでは，いくつかポイントを解説してみます。
まず，定義の中で「多様な子どもたち（排除されやすい子どもたちを含む）の教育を受ける権利」という言葉に注目しましょう。
インクルーシブ教育は多様な子どもたちの**教育を受ける権利**を保障するためのものです。
教育を受ける権利は基本的人権に含まれるもので，誰もが持っているものです。

なぜこのようなことを明言する必要があるかというと，障害児を含む多様な子どもたちは現行の教育システムから排除されやすいからに他なりません。
例えば，自閉スペクトラム症がある人は一般に聴覚的情報よりも視覚的情報の処理を得意としていて，指示が口頭のみで出される場合には活動にうまく参加できないことが多々あります。
しかしながら，学校では指示が口頭のみで出されることが少なくありません。
このような場合には，自閉スペクトラム症の人は活動にうまく参加できずに教育を受ける権利が十分に保証されているとはいえないでしょう。

もう一つ注目してほしいポイントは「教育システムそのものを改革していくプロセス」という箇所です。
全ての子どもたちの教育の権利を保障する過程ではうまくいった取り組みもあればうまくいかない取り組みもあるはずです。
その中では教育内容やその指導の方略を見直して変更・修正していく必要が常にあります。
多様なニーズを持つ子どもたちの権利を保障するという理念に基づき，絶えず良い方法を模索し続けるその過程こそがインクルーシブ教育だということです。


## 障害者の権利に関する条約

障害者の権利に関する条約（通称，障害者権利条約）は21世紀初の人権条約です。
2006に国連総会において採択されました。
日本政府は翌年2007年に署名をし，様々な国内法を整えた上で2014年に批准しました[^syomei]。

[^syomei]: 「署名」とは条約の趣旨や内容について基本的な賛意を表明することを意味します。
署名後には国会の承認を経て，条約に拘束されることについて国が同意を表明します。
このことを「批准」と言います（より正確には批准は締結の方法の一種です）。
批准後に条約の効力が発生します。


### 位置付け

この条約の採択以前にも，1971年の「知的障害者の権利宣言」，1975年の「障害者の権利宣言」，1982年の「障がい者に関する世界行動計画」など，障害者の人権についての国際的な取り組みが行われてきましたが，これらには法的な拘束力がありませんでした。

それに対して障害者権利条約は法的な拘束力があります。
この条約が国連総会において採択されたことは，各国の障害者に対する取り組みを推進する点で大きな意義があることでした。

### 特徴

障害者権利条約で重視されている点に合理的配慮があります。
この概念は特に重要なので，次節で詳しく取り上げます。

この条約の特色としては，条約で定められた事項を各国が実行しているかをモニタリングする仕組みが規定に盛り込まれている点が挙げられます。
条約締結国は，締結後に条約の実施状況をまとめた報告書を作成して，障害者権利委員会に報告することが求められています。
また，報告書に対して出された懸念や疑問点に対しては回答を行う必要があります。
その後に，委員会は総括所見を公開する形で各国における条約の実施状況がモニタリングされる仕組みになっています。

日本政府に対する総括所見は2022年に公開され，様々な領域にわたって90項目以上が改善するよう勧告されました[^dpi]。
総括所見の日本政府による仮訳は[外務省のウェブサイト](https://www.mofa.go.jp/mofaj/gaiko/jinken/index_shogaisha.html)で読むことができます。

[^dpi]: DPI日本会議（2022）． 障害者権利委員会から日本政府へ勧告（総括所見）が出されました！ ～90項目以上改善するよう勧告されています～ [［リンク］](https://www.dpi-japan.org/blog/workinggroup/crpd/recommendations-for-japan/) アクセス日: 2024年8月22日

日本障害者協議会（Japan Council on Disability）は，ウェブサイト上に各国の国際審査の過程を日本語訳したものを掲載しています。
条約の実施状況のモニタリングの実際が知りたい人は見てみるとよいでしょう。

また，障害者権利条約の別の特色を表す言葉の一つが「**私たちのことを私たち抜きに決めないで（Nothing about us without us!）**」というスローガンです。

日本は障害者権利条約締結に向けた国内法の整備のために内閣に「障がい者制度改革推進本部」を設置し，障害者施策の推進に関する事項について意見を求めるための「障がい者制度改革推進会議」を設置しました。
このときの会議の構成員24名のうち14名が障害がある当事者やその家族でした。
これはスローガンにあるように障害者施策について，障害者当事者が決めていくという条約の理念を反映したものでした。
当時の議事録は[Web上](https://www8.cao.go.jp/shougai/suishin/kaikaku/kaikaku.html)ですべて読めるので興味がある人はぜひ覗いてみると良いでしょう。


## 合理的配慮

障害者権利条約は，主要人権条約の中で初めて**合理的配慮**（reasonable accomodation）という文言を用いました[^gouriteki]。
さらに，合理的配慮を否定すること（合理的配慮の不提供）は差別であると定めました。
この概念は障害者権利を保障する手段として極めて重要です。

[^gouriteki]: @kawashima2016 [p.22]によればこの用語はもともと1960年代半ばのアメリカや1980年代半ばのカナダで宗教差別に関連した用語として使われ始めました。その後，1990年の障害をもつアメリカ人法によって世界に広がりました。

障害者権利条約において，合理的配慮を提供しないことは障害者への差別に当たると考えられています。
日本では2013年に制定された「障害者を理由とする差別の解消の推進に関する法律」（通称: 差別解消法）において，学校や役所等の行政機関において合理的配慮の提供が義務化されて，2021の改正において一般の事業者においても義務化されました。

### 合理的配慮とは

内閣府が啓発用に発行している[リーフレット](https://www8.cao.go.jp/shougai/suishin/sabekai_leaflet.html)である『「合理的配慮」を知っていますか？』では，合理的配慮の提供は次のように説明されています。

::: {.callout-note}
## 合理的配慮の提供の説明

障害のある人は、社会の中にあるバリアによって生活しづらい場合があります。

この法律では、役所や事業者に対して、障害のある人から、社会の中にあるバリアを取り除くために何らかの対応を必要としているとの意思が伝えられたとき（※）に、負担が重すぎない範囲で対応すること（事業者においては、対応に努めること）を求めています。

※ 言語（手話を含む。）、点字、拡大文字、筆談、実物を示すことや身振りなどのサインによる合図、触覚など様々な手段により意思が伝えられることをいいます。通訳や障害のある人の家族、支援者、介助者、法定代理人など、障害のある人のコミュニケーションを支援する人のサポートにより本人の意思が伝えられることも含まれます。
:::

この説明における1つ目のポイントは「社会の中にあるバリアを取り除くために何らかの対応を必要としているとの意思が伝えられたとき」の箇所です。
合理的配慮というのは，個別・具体的に何かしらのバリアを取り除くために提供されるものだということです。

この説明の2つ目のポイントは「負担が重すぎない範囲で」の箇所です。
例えば，車椅子の利用者で2階にあるレストランへと入店できない人が，自分のためにエレベーターを設置してほしいと求めても，店にとっては負担が重すぎるため，この対応をする必要はありません。

ただし，この場合でも店側はレストランへと入店したいという障害のある人のニーズを汲み取った上でどのような対応なら可能かを話し合う必要がありません。
障害がある人と事業者が行うこのような対話は**建設的対話**と呼ばれます。
「負担が重すぎない範囲で」というのは事業者が対応しないための言い訳にはならないので注意しましょう。

学校の文化によっては，合理的配慮を検討する際に「前例がありません」や「特別扱いできません」といった理由（?）で，対応がなされないことがあります。
しかし，こうした対応は内閣府が差別解消法の改正に際して作成した[リーフレット](https://www8.cao.go.jp/shougai/suishin/sabekai_leaflet-r05.html)においても，**対話の際に避けるべき考え方**として紹介されています。
合理的配慮は，障害のある人が教育を受ける権利を保障するものという基本的な考え方に立ち返って必要な対応を検討するべきでしょう。


::: {.callout-caution}
## 課題

内閣府の[リーフレット](https://www8.cao.go.jp/shougai/suishin/sabekai_leaflet-r05.html)を参照して，合理的配慮の具体例や建設的対話の具体例を確認してみましょう。
:::

:::{.callout-tip title="合理的配慮という語について"}

合理的配慮という語の「配慮」という語が日本語だと「やってあげる」ニュアンスを含むため，この訳語があまり適切でないのという議論があります。

@kobayashi2013 は reasonable accomodation の意味を正しく表現するために「現実的な調整」「理性的かつ変化し得る妥協」「双方合意の適切な環境調整」「相互努力による適度な調整」といった訳語を提案しています。

この概念を理解するときには，「配慮」という言葉に引きづられないことが重要でしょう。
:::


## 参考資料
### ウェブ上で見ることができる映像等
より深く考えるためにウェブ上で見ることができる資料をいくつか紹介します。

- 街へ出よ－福祉への反逆－[前編](https://www.youtube.com/watch?v=AOq2IgmbtB8) [後編](https://www.youtube.com/watch?v=O3WPcr1SGEw)  
    1977年に脳性マヒ者の当事者団体である全国青い芝の会が展開した「バス闘争」についてドキュメンタリー映像です。
    現在では車椅子の人がバスに乗って一人で移動することは当たり前に行われていますが，当時は車椅子の人がバスに乗るためには必ず付き添いの人が必要でした。
    マジョリティ向けに作られている社会に対して異議申し立てを行う過去があって，現在の仕組みは作られています。

- [Educating Peter](https://www.youtube.com/watch?v=3bI-igJFt_k)  
    1992年のアカデミー章短編ドキュメンタリー映画賞を受賞した作品です。
    ダウン症がある小学校3年生ピーターが通常学級に転籍した1年のドキュメンタリー映像です。
    最初は教室の中で問題を起こしていたピーターが適用して徐々に周りの児童たちを変えていった様子が描かれています。  
    障害がない子どもとある子どもが一緒に学ぶインクルーシブ教育のポジティブな面を象徴的に描く一方で，サクセスストーリとして描きすぎている，成功のために必要とされる人的な支援や環境的な支援について描かれていない等の批判もあったようです[@mizuuchi2023, p.59]。  
    ※ 設定ボタンから自動翻訳機能をつかって日本語字幕をつけることもできます。

## 補足資料（★）


